/**
 * Automatically generated types for motia
 * Do NOT edit this file manually.
 * 
 * Consider adding this file to .prettierignore and eslint ignore.
 */
import { EventHandler, ApiRouteHandler, ApiResponse, MotiaStream, CronHandler } from 'motia'

declare module 'motia' {
  interface FlowContextStateStreams {
    
  }

  interface Handlers {
    'StateAuditJob': CronHandler<{ topic: 'notification'; data: { template_id: string; email: string; template_data: Record<string, unknown> } }>
    'ProcessFoodOrder': EventHandler<{ email: string; quantity: unknown; pet_id: string }, { topic: 'notification'; data: { template_id: string; email: string; template_data: Record<string, unknown> } }>
    'Notification': EventHandler<{ template_id: string; email: string; template_data: Record<string, unknown> }, never>
    'ApiTrigger': ApiRouteHandler<{ pet: unknown; foodOrder?: unknown | unknown }, ApiResponse<200, { id: string; name: string; photoUrl: string }>, { topic: 'process-food-order'; data: { email: string; quantity: unknown; pet_id: string } }>
  }
    
}