/**
 * Automatically generated types for motia
 * Do NOT edit this file manually.
 * 
 * Consider adding this file to .prettierignore and eslint ignore.
 */
import { EventHandler, ApiRouteHandler, ApiResponse, MotiaStream, CronHandler } from 'motia'

declare module 'motia' {
  interface FlowContextStateStreams {
    
  }

  interface Handlers {
    'Research Status API': ApiRouteHandler<Record<string, unknown>, unknown, never>
    'Web Search': EventHandler<never, { topic: 'search-results-collected'; data: never }>
    'Deep Research API': ApiRouteHandler<Record<string, unknown>, unknown, { topic: 'research-started'; data: never }>
    'Research Report API': ApiRouteHandler<Record<string, unknown>, unknown, never>
    'Generate Search Queries': EventHandler<never, { topic: 'search-queries-generated'; data: never }>
    'Follow-up Research': EventHandler<never, { topic: 'search-queries-generated'; data: never }>
    'Extract Web Content': EventHandler<never, { topic: 'content-extracted'; data: never }>
    'Compile Research Report': EventHandler<never, never>
    'Analyze Content': EventHandler<never, { topic: 'analysis-completed'; data: never } | { topic: 'follow-up-research-needed'; data: never }>
  }
}