/**
 * Automatically generated types for motia
 * Do NOT edit this file manually.
 * 
 * Consider adding this file to .prettierignore and eslint ignore.
 */
import { EventHandler, ApiRouteHandler, ApiResponse, MotiaStream, CronHandler } from 'motia'

declare module 'motia' {
  interface FlowContextStateStreams {
    
  }

  interface Handlers {
    'User Log API': ApiRouteHandler<Record<string, unknown>, unknown, never>
    'Source Validation API': ApiRouteHandler<Record<string, unknown>, unknown, never>
    'Source Mode API': ApiRouteHandler<Record<string, unknown>, unknown, never>
    'Source Details API': ApiRouteHandler<Record<string, unknown>, unknown, never>
    'Source Chat API': ApiRouteHandler<Record<string, unknown>, unknown, never>
    'Source Action API': ApiRouteHandler<Record<string, unknown>, unknown, never>
    'Research Query API': ApiRouteHandler<Record<string, unknown>, unknown, never>
    'Report Feedback API': ApiRouteHandler<Record<string, unknown>, unknown, never>
  }
    
}